[package]
name = "simple_ode_by_de"
version = "0.1.0"
edition = "2021"

[dependencies]
GSL = "7.0.0"
itertools = "0.13.0"
lapack = { version = "0.11.0", default-features = false, features = ["accelerate"] }
colored = "2.1.0"
colors-transform = "0.2.11"
plotly = "0.8.4"
faer_gmres = "0.0.4"